### ISSUE TITLE
build step and entrypoint variable not working correctly

### ISSUE THREAD

**Issue by ionutnechita** [intel/Edge-Software-Provisioner#13]
Hi ESP Team,

I try to use this step: (8/9) Building custom files for <PROFILE>... under Ubuntu 20.04 profile, but not working.
I think is one issue with entrypoint variable in scripts/bulkfileutils.sh.
Because of this, the docker container is no longer turned on.

ESP: branch master.

```
// profile - cat conf/files.yml
---

build:
  # Identify the container to run the build process in
  - container: ubuntu:20.04
    entrypoint:
    # Interrupter to use for execution
    cmd: /usr/bin/bash -c
    # Script to run from the /build/ folder
    execute: start.sh

// esp - git diff scripts/bulkfileutils.sh
@@ -252,10 +252,10 @@ processBuilds() {
                 local container=${files_config_build__container[j]}
                 validateInput container "${container}" "'container' in files.yml of profile ${profileName} is not valid container name: ${container}"
             fi
-            if [ "${files_config_build__entrypoint[j]}" == '""' ]; then
+            if [ -z "${files_config_build__entrypoint[j]+x}" ]; then
                 local entrypoint=""
             else
-                local entrypoint="--entrypoint=\"${files_config_build__entrypoint[j]}\""
+                local entrypoint="${files_config_build__entrypoint[j]}"
             fi
             if [ -z "${files_config_build__cmd[j]+x}" ]; then
                 local cmd="sh -c"
@@ -301,4 +301,4 @@ processEmbeddeds() {
         printDatedMsg "  ${T_INFO_ICON} No files to embed into uOS"
         logMsg "No files to embed into uOS"
     fi
-}
\ No newline at end of file
+}

```

**Comment by brod-intel** [comment]
Problem is entrypoint: is missing double quotes or a null.  The conf/files.yml should look like:
```
build:
  # Identify the container to run the build process in
  - container: ubuntu:20.04
    entrypoint: ""
    # Interrupter to use for execution
    cmd: /usr/bin/bash -c
    # Script to run from the /build/ folder
    execute: start.sh
```
